CREATE DATABASE japarphantom DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE japarphantom;

--  username password
CREATE TABLE thedoor (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  door_name VARCHAR(255) UNIQUE NOT NULL,
  door_pwd VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

-- author information
CREATE TABLE auth_inf (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  auth_inf_uid INTEGER UNIQUE NOT NULL,
  auth_name VARCHAR(255) UNIQUE NOT NULL,
  wcount INTEGER UNSIGNED NULL,
  artcount INTEGER UNSIGNED NULL,
  enjoy INTEGER UNSIGNED NULL,
  FOREIGN KEY (auth_inf_uid) REFERENCES thedoor (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

-- article information
CREATE TABLE art_inf (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  art_inf_uid INTEGER UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  arttitle TEXT(65535) NOT NULL,
  bcontexts TEXT(65535) NOT NULL,
  tag CHAR(215) NULL,
  rcount INTEGER UNSIGNED NULL,
  awesome INTEGER UNSIGNED NULL,
  oppose INTEGER UNSIGNED NULL,
  FOREIGN KEY (art_inf_uid) REFERENCES auth_inf (auth_inf_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;
